"""Added foreign key from Booking to Accommodations

Revision ID: 448b80ede7cf
Revises: a268aa16e107
Create Date: 2025-02-21 15:44:37.438604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448b80ede7cf'
down_revision = 'a268aa16e107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accommodation_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_booking_accommodation', 'accommodations', ['accommodation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('accommodation_id')

    # ### end Alembic commands ###
