"""add column to bookings

Revision ID: 902cd52c1720
Revises: baf996e7b21e
Create Date: 2025-03-04 23:28:51.288640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902cd52c1720'
down_revision = 'baf996e7b21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
